spring.application.name=b2b
server.port=8080

spring.datasource.url=jdbc:mysql://mysql-1786ff4c-ticochearodriguez-d88a.g.aivencloud.com:16835/sistema_b2b?ssl-mode=REQUIRED

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.datasource.hikari.connection-timeout=5000
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
decolecta.api.token=sk_15383.G5bYk6i8aWIeF4PXyuHYwWJWVoKf5fVj

upload.path=C:/uploads/b2b/comprobantes/