spring.application.name=b2b
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://mysql-1786ff4c-ticochearodriguez-d88a.g.aivencloud.com:16835/sistema_b2b?ssl-mode=REQUIRED

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

jwt.secret=${JWT_SECRET:default}
jwt.expiration=86400000

decolecta.api.token=${DECOLECTA_API_TOKEN:sk_15383.G5bYk6i8aWIeF4PXyuHYwWJWVoKf5fVj}

upload.path=${UPLOAD_PATH:/tmp/uploads/b2b/comprobantes/}